spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: quizdb

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: debug
